version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartak1
      - POSTGRES_DB=balance
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes: 
      - .database/postgres/data:/var/lib/postgresql/data

  api:
    build:
      context: ../.
      dockerfile: build/Dockerfile
    ports:
      - "4000:4000"
    depends_on: 
      - db
    networks:
      - backend
    volumes:
      - ../.:/go/src/api
    restart: always

networks:
  backend:

